# ANX 603 :  Python for Data Analytics
## Assignment 3  - Due Wednesday 9/7/2022, at 11:59 pm ( 10 points in total)
## Instructor : Dr. Ali Dag

## Each question is worth 1 point. 

### Note  Please note that the output that you should obtain is given below each question !, So take the advantage of it !

#### Note : Submit .ipynb (this) file to the canvas. Name your .ipynb file as “Yourname_Assignment2.ipynb" before submitting.

While working on the assignment;
- Use your judgement
- State your assumptions (what do you understand)
- Solve the problem

Good luck!


In [2]:
# Question 1 : Create a function that counts the number of times the word "cat" occurs in a string. 
# Don't worry about edge cases like a punctuation being attached to the word cat, 
# but do account for capitalization (CAT, cat, Cat, ....regarless of the case) **


    # Example :  countCat('A Cat is a cat and that is that!')  >>>=== 2


    
    
countCat('A Cat is a cat and that is that!')

2

In [9]:
#format the string before processing it - remove captialize and process it one piece at a time

def catcounter(x):
    x=x.lower()
    x=x.split()
    counter=0
    for i in x:
            if i=="cat":
                counter=counter +1
    
    print(counter)


In [8]:
catcounter('A Cat is a cat and that is that!')

2


In [4]:
# Question 2: Implement a function that takes a single parameter x (an integer) 
# and calculates sum of all of the numbers between 0 and that integer (inclusive).

# Example :
             
    # sum_num(5) >>>====  15 (0+1+2+3+4+5)
    # sum_num(2) >>>====  3 (0+1+2)
    
    
sum_num(5)

15

In [11]:
#import numpy in function

def sum_num(x):
    import numpy as np
    x=x+1
    print(sum(np.arange(1,x)))

In [12]:
sum_num(5)

15


In [6]:
# Exercise 3: Implement a function called filter_less_than() that takes a list of words 
# and returns list of words with the length less than or equal to 5 characters.



# Example:

#[IN]: filter_less_than(['Creighton', 'Heider', 'Omaha'])
#[OUT]: ['Creighton']


filter_less_than(['Creighton', 'Heider', 'Omaha'])


['Omaha']

In [19]:
#don't need to split because commas split it 

def filter_less_than(x):
    for i in x:
        if len(i)<=5:
            print(i)

In [20]:
filter_less_than(['Creighton', 'Heider', 'Omaha'])

Omaha


In [8]:
# Exercise 4: Implement a function called find_shortest_word() that takes a single parameter x (a string) 
# and returns the shortest word in the sentence (string) 

    # Example:

   #[IN]: find_shortest_word(['Everybody in this class love learning functions''])
   #[OUT]: ['in']
    
    
find_shortest_word('Everybody in this class love learning functions')

'in'

In [21]:
#split to check each word
def find_shortest_word(x):
    x=x.split()
    x=sorted(x, key=lambda el: len(el))
    print(x[0])

In [22]:
find_shortest_word('Everybody in this class love learning functions')

in


In [12]:
# Question 5 : Assuem that you are driving a little too fast, and a police officer stops you. 
# Write a function to return one of 3 possible results: 
# 1) "Happy ending", "Not so happy ending!", or "Sad story".
# If your speed is 65 or less, the result is "Happy ending". 

# If speed is between 66 and 75 inclusive, the result is "Not so happy ending!". 

# If speed is 76 or more, the result is "Sad story". 

# Unless it is your birthday (encoded as a boolean value in the parameters of the function) -- on your birthday, 
# your speed can be 5 higher in all cases. *



   # Example : 
    
    #     caught_speeding(70, True)   >>>=== 'Happy ending'
    #     caught_speeding(70, False)   >>>=== 'Not so happy ending!'



print(caught_speeding(70, True))
print(caught_speeding(70, False))


Not so happy ending!
Happy ending


In [26]:
def caught_speeding(x,y):
    if y==True and x<=70:
        print("Happy Ending!")
    elif y==True and 71<=x<=80:
        print("Not so Happy Ending!")
    elif y==True and x>80:
        print("Sad story")
    elif y==False and x<=65:
        print("Happy Ending!")
    elif y==False and 66<=x<=75:
        print("Not so Happy Ending!")
    elif y==False and x>75:
        print("Sad story")

#the question has an error. the example is correct and my answer reflects the example however the given outputs don't make sense
# the given solution should be reversed. If its your birthday and you were going 70 this would be true and be a happy ending
# your solution would ask "is it not your birthday" if it wasn't there birthday it would be true.

In [27]:
caught_speeding(70,True)
caught_speeding(70, False)

Happy Ending!
Not so Happy Ending!


In [28]:
# Question 6: Generate a 3 by 4 matrix that consists of random numbers sampled from a standard normal distribution

In [30]:
import numpy as np
np.random.randn(3,4)

array([[ 0.77333658, -0.30460069,  1.15407016,  0.53942909],
       [ 0.00568102, -0.72295806,  1.3228536 ,  2.16103218],
       [-0.19510447, -0.08450523,  0.57723744,  0.04604589]])

In [31]:
# Question 7:  Create the following matrix using numpy

np.arange(0.1,2.1,.1).reshape(4,5)

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ],
       [1.1, 1.2, 1.3, 1.4, 1.5],
       [1.6, 1.7, 1.8, 1.9, 2. ]])

### For questions 8, 9 and 10, use the "my_array_1" array that is created in the cell below.

In [32]:
np.random.seed(123)
my_array_1 = np.random.randint(1,16,15).reshape(3,5)
my_array_1

array([[15, 14, 15,  3, 13],
       [ 3,  7,  2,  4, 11],
       [12, 10,  7,  2,  1]])

In [17]:
# Question 8 :  Write the code (indexing/slicing) below that generates the new matrix below it.


array([[ 2,  4, 11],
       [ 7,  2,  1]])

In [33]:
my_array_1[1:3,2:5]

array([[ 2,  4, 11],
       [ 7,  2,  1]])

In [18]:
# Question 9 : Write the code (indexing/slicing) below that generates the new matrix below it.



array([[14, 15],
       [ 7,  2]])

In [34]:
my_array_1[0:2,1:3]

array([[14, 15],
       [ 7,  2]])

In [19]:
# Question 10 :

#### Step 1:  Get the sum of all the values in my_array_1
#### Step 2:  Get the standard deviation of the values in my_array_1
#### Step 3:  Get the sum of all the columns in my_array_1




119
5.012872319228657
[30 31 24  9 25]


In [35]:
print(my_array_1.sum())
print(my_array_1.std())
print(my_array_1.sum(axis=0))

119
5.012872319228657
[30 31 24  9 25]
